################################################################################
################################################################################
##																			  ##
##                     			    SANKEY 	     							  ##
##																			  ##
################################################################################
################################################################################


print "--------- SAVING SANKEY --------";

## Generate CSV file to be used as input to Sankey diagram
# Notes:
# - Assuming that SNG and BioOil are used in boilers
printf "%s,%s,%s,%s,%s,%s\n", "source" , "target", "realValue", "layerID", "layerColor", "layerUnit" > (PathName & "/sankey/input2sankey.csv");

#------------------------------------------
# SANKEY - RESOURCES
#------------------------------------------
## Ammonia
    # AMMONIA and AMMONIA_RE
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["AMMONIA", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Ammonia (0)" , "Ammonia (8)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["AMMONIA","AMMONIA"] * F_t ["AMMONIA", h, td]  ) / 1000 , "Ammonia",
    "#000ECD", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["AMMONIA_RE", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Ammonia RE (0)" , "Ammonia (8)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["AMMONIA_RE","AMMONIA"] * F_t ["AMMONIA_RE", h, td]  ) / 1000 , "Ammonia",
    "#000ECD", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
    # AMMONIA to NED
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (End_uses ["AMMONIA", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Ammonia (8)" , "Non-energy demand", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            End_uses ["AMMONIA", h, td]   / 1000 , "Ammonia",
    "#000ECD", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
    # HABER_BOSCH
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["HABER_BOSCH", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2 (9)" , "Haber-Bosch (10)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (-layers_in_out["HABER_BOSCH","H2 (9)"] * F_t ["HABER_BOSCH", h, td]  ) / 1000 , "H2 (9)",
    "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Haber-Bosch (10)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (-layers_in_out["HABER_BOSCH","ELECTRICITY"] * F_t ["HABER_BOSCH", h, td]  ) / 1000 , "Electricity",
    "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Haber-Bosch (10)" , "DHN", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["HABER_BOSCH","HEAT_LOW_T_DHN"] * F_t ["HABER_BOSCH", h, td]  ) / 1000 , "DHN",
    "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Haber-Bosch (10)" , "Ammonia  (8)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["HABER_BOSCH","AMMONIA"] * F_t ["HABER_BOSCH", h, td]  ) / 1000 , "Ammonia",
    "#000ECD", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
    # AMMONIA to CCGT
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["CCGT_AMMONIA", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Ammonia (8)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (-layers_in_out["CCGT_AMMONIA","AMMONIA"] * F_t ["CCGT_AMMONIA", h, td]  ) / 1000 , "Ammonia",
    "#000ECD", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
    # AMMONIA to H2
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["AMMONIA_TO_H2", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Ammonia (8)" , "H2", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (-layers_in_out["AMMONIA_TO_H2","AMMONIA"] * F_t ["AMMONIA_TO_H2", h, td]  ) / 1000 , "H2",
    "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}

## Methanol
    # METHANOL and METHANOL_RE
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["METHANOL", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Methanol (1)" , "Methanol (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["METHANOL","METHANOL"] * F_t ["METHANOL", h, td]  ) / 1000 , "Methanol",
    "#CC0066", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["METHANOL_RE", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Methanol RE (1)" , "Methanol (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["METHANOL_RE","METHANOL"] * F_t ["METHANOL_RE", h, td]  ) / 1000 , "Methanol",
    "#CC0066", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}

    # METHANE_TO_METHANOL
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["METHANE_TO_METHANOL", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "Methane-to-Methanol (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["METHANE_TO_METHANOL","GAS"] * F_t ["METHANE_TO_METHANOL", h, td]  ) / 1000 , "GAS", "#FFD700", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Methane-to-Methanol (6)" , "Methanol (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["METHANE_TO_METHANOL","METHANOL"] * F_t ["METHANE_TO_METHANOL", h, td]  ) / 1000 , "Methanol", "#CC0066", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    }

    # BIOMASS_TO_METHANOL
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["BIOMASS_TO_METHANOL", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wood (1)" , "Gasifi. to Methanol (5)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["BIOMASS_TO_METHANOL","WOOD"] * F_t ["BIOMASS_TO_METHANOL", h, td]  ) / 1000 , "Wood", "#CD853F", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gasifi. to Methanol (5)" , "Elec", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["BIOMASS_TO_METHANOL","ELECTRICITY"] * F_t ["BIOMASS_TO_METHANOL", h, td]  ) / 1000 , "Electricity", "#00BFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gasifi. to Methanol (5)" , "DHN", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["BIOMASS_TO_METHANOL","HEAT_LOW_T_DHN"] * F_t ["BIOMASS_TO_METHANOL", h, td]  ) / 1000 , "DHN", "#FA8072", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gasifi. to Methanol (5)" , "Methanol (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["BIOMASS_TO_METHANOL","METHANOL"] * F_t ["BIOMASS_TO_METHANOL", h, td]  ) / 1000 , "Methanol", "#CC0066", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    }

    # SYN_METHANOLATION
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["SYN_METHANOLATION", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2" , "Methanolation (10)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["SYN_METHANOLATION","WOOD"] * F_t ["SYN_METHANOLATION", h, td]  ) / 1000 , "H2", "#FF00FF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Methanolation (10)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["SYN_METHANOLATION","ELECTRICITY"] * F_t ["SYN_METHANOLATION", h, td]  ) / 1000 , "Electricity", "#00BFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Methanolation (10)" , "DHN (11)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["SYN_METHANOLATION","HEAT_LOW_T_DHN"] * F_t ["SYN_METHANOLATION", h, td]  ) / 1000 , "DHN", "#FA8072", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Methanolation (10)" , "Methanol (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["SYN_METHANOLATION","METHANOL"] * F_t ["SYN_METHANOLATION", h, td]  ) / 1000 , "Methanol", "#CC0066", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    }

    # METHANOL_TO_NED
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (End_uses ["METHANOL", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Methanol (7)" , "Non-energy demand", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            End_uses ["METHANOL", h, td]   / 1000 , "Methanol",
    "#CC0066", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
## HERE ##
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["CAR_METHANOL", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Methanol (7)" , "Mob priv", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["CAR_METHANOL","METHANOL"] * F_t ["CAR_METHANOL", h, td]  ) / 1000 , "Methanol",
        "#CC0066", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} ((F_t ["BUS_COACH_DIESEL", h, td] +
F_t["BUS_COACH_HYDIESEL", h, td])  ) > 10 then
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} ((F_t ["BOAT_FREIGHT_METHANOL", h, td]  )  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Methanol (7)" , "Freight", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["BOAT_FREIGHT_METHANOL","METHANOL"] * F_t ["BOAT_FREIGHT_METHANOL", h, td] ) / 1000 , "Methanol (7)", "#CC0066", "TWh"
        > (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} ((F_t ["TRUCK_METHANOL", h, td] + F_t ["TRUCK_METHANOL", h, td] )  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Methanol (7)" , "Freight", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["TRUCK_METHANOL","METHANOL"] * F_t ["TRUCK_METHANOL", h, td]  -layers_in_out["TRUCK_METHANOL","METHANOL"] * F_t ["TRUCK_METHANOL", h, td]  ) / 1000 , "Methanol (7)", "#CC0066", "TWh"
        > (PathName & "/sankey/input2sankey.csv");

## HVC
    # OIL_TO_HVC
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["OIL_TO_HVC", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Oil (1)", "NSC", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (-layers_in_out["OIL_TO_HVC","LFO"] * F_t ["OIL_TO_HVC", h, td]  ) / 1000 , "Naphtha",
    "#8B008B", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "NSC", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (-layers_in_out["OIL_TO_HVC","ELECTRICITY"] * F_t ["OIL_TO_HVC", h, td]  ) / 1000 , "Electricity",
    "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Heat HT (7)" , "NSC(5)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(- layers_in_out["OIL_TO_HVC","HEAT_HIGH_T"] * F_t ["OIL_TO_HVC", h, td]  ) / 1000 ,
        "Heat HT", "#DC143C", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "NSC (5)", "HVC (8)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["OIL_TO_HVC","HVC"] * F_t ["OIL_TO_HVC", h, td]  ) / 1000 , "HVC",
    "#00FFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    }

    # GAS_TO_HVC
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["GAS_TO_HVC", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "OCM (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["GAS_TO_HVC","GAS"] * F_t ["GAS_TO_HVC", h, td]  ) / 1000 , "GAS", "#FFD700", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "OCM (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["GAS_TO_HVC","ELECTRICITY"] * F_t ["GAS_TO_HVC", h, td]  ) / 1000 , "Electricity", "#00BFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "OCM (6)" , "HVC (8)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["GAS_TO_HVC","HVC"] * F_t ["GAS_TO_HVC", h, td]  ) / 1000 , "HVC", "#00FFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    }

    # BIOMASS_TO_HVC
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["BIOMASS_TO_HVC", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wood (1)" , "Gasifi. to HVC (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["BIOMASS_TO_HVC","WOOD"] * F_t ["BIOMASS_TO_HVC", h, td]  ) / 1000 , "Wood", "#CD853F", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Gasifi. to HVC (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["BIOMASS_TO_HVC","ELECTRICITY"] * F_t ["BIOMASS_TO_HVC", h, td]  ) / 1000 , "Electricity", "#00BFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Heat HT (7)" , "Gasifi. to HVC (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(- layers_in_out["BIOMASS_TO_HVC","HEAT_HIGH_T"] * F_t ["BIOMASS_TO_HVC", h, td]  ) / 1000 ,
        "Heat HT", "#DC143C", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gasifi. to HVC" , "HVC", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["BIOMASS_TO_HVC","HVC"] * F_t ["BIOMASS_TO_HVC", h, td]  ) / 1000 , "HVC", "#00FFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    }

    # METHANOL_TO_HVC
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["METHANOL_TO_HVC", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Methanol (7)" , "MTO", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["METHANOL_TO_HVC","METHANOL"] * F_t ["METHANOL_TO_HVC", h, td]  ) / 1000 , "Methanol (7)", "#CC0066", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Heat HT (7)" , "MTO", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(- layers_in_out["METHANOL_TO_HVC","HEAT_HIGH_T"] * F_t ["METHANOL_TO_HVC", h, td]  ) / 1000 ,
        "Heat HT", "#DC143C", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "MTO" , "HVC", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["METHANOL_TO_HVC","HVC"] * F_t ["METHANOL_TO_HVC", h, td]  ) / 1000 , "HVC", "#00FFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    }


    # HVC_TO_NED
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (End_uses ["HVC", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "HVC (8)" , "Non-energy demand", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            End_uses ["HVC", h, td]   / 1000 , "HVC", "#00FFFF", "TWh"
    >> (PathName & "/sankey/input2sankey.csv");
}


## Gasoline
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["GASOLINE", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Gasoline (0)" , "Gasoline (1)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["GASOLINE","GASOLINE"] * F_t ["GASOLINE", h, td]  ) / 1000 , "Gasoline (1)",
    "#808080", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gasoline (1)", "Mob priv", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["CAR_GASOLINE","GASOLINE"] * F_t ["CAR_GASOLINE", h, td]  + layers_in_out["CAR_HEV","GASOLINE"] * F_t ["CAR_HEV", h, td]   + layers_in_out["CAR_PHEV","GASOLINE"] * F_t ["CAR_PHEV", h, td]  ) / 1000 , "Gasoline (1)",
    "#808080", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    }
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["BIOETHANOL", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Bio-ethanol (0)" , "Gasoline (1)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            (layers_in_out["BIOETHANOL","GASOLINE"] * F_t ["BIOETHANOL", h, td]  ) / 1000 , "Gasoline (1)",
    "#808080", "TWh" >> (PathName & "/sankey/input2sankey.csv");

## Diesel
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["DIESEL", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Diesel (0)" , "Diesel (1)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["DIESEL","DIESEL"] * F_t ["DIESEL", h, td]  ) / 1000 , "Diesel (1)",
        "#D3D3D3", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["BIODIESEL", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Bio-diesel (0)" , "Diesel (1)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["BIODIESEL","DIESEL"] * F_t ["BIODIESEL", h, td]  ) / 1000 , "Diesel (1)",
        "#D3D3D3", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["CAR_DIESEL", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Diesel (1)" , "Mob priv", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["CAR_DIESEL","DIESEL"] * F_t ["CAR_DIESEL", h, td]  ) / 1000 , "Diesel (1)",
        "#D3D3D3", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} ((F_t ["BUS_COACH_DIESEL", h, td] +
F_t["BUS_COACH_HYDIESEL", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Diesel (1)" , "Mob public", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["BUS_COACH_DIESEL","DIESEL"] * F_t ["BUS_COACH_DIESEL", h, td]   -
        layers_in_out["BUS_COACH_HYDIESEL","DIESEL"] * F_t ["BUS_COACH_HYDIESEL", h, td]   ) / 1000 , "Diesel (1)", "#D3D3D3", "TWh"
        > (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} ((F_t ["TRUCK_DIESEL", h, td] + F_t ["BOAT_FREIGHT_DIESEL", h, td] )  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Diesel (1)" , "Freight", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["TRUCK_DIESEL","DIESEL"] * F_t ["TRUCK_DIESEL", h, td]  -layers_in_out["BOAT_FREIGHT_DIESEL","DIESEL"] * F_t ["BOAT_FREIGHT_DIESEL", h, td]  ) / 1000 , "Diesel (1)", "#D3D3D3", "TWh"
        > (PathName & "/sankey/input2sankey.csv");

## Gas (natural & synthetic)
if sum {t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["GAS", h, td] * t_op [h, td]) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Gas (1)" , "Gas (5)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(F_t ["GAS", h, td] * t_op [h, td]) / 1000 , "GAS", "#FFD700", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");

if sum {t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["GAS_RE", h, td] * t_op [h, td]) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Gas RE (1)" , "Gas (5)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(F_t ["GAS_RE", h, td] * t_op [h, td]) / 1000 , "GAS", "#FFD700", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
        # SNG use:
 # Storage?
if F ["GAS_STORAGE"] > 0.001 then {
        printf "%s,%s,%.2f,%s,%s,%s\n", "Gas Prod (3)" , "Gas sto. (4)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(Storage_in["GAS_STORAGE", "GAS", h, td]  ) / 1000 ,
        "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");
        printf "%s,%s,%.2f,%s,%s,%s\n", "Gas sto. (4)" , "Gas (5)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(Storage_out["GAS_STORAGE", "GAS", h, td]*storage_eff_out ["GAS_STORAGE","GAS"]  ) / 1000 ,
        "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");
        printf "%s,%s,%.2f,%s,%s,%s\n", "Gas Prod (3)" , "Gas (5)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}( layers_in_out["GASIFICATION_SNG","GAS"] * F_t ["GASIFICATION_SNG", h, td] + layers_in_out["BIOMETHANATION","GAS"] * F_t ["BIOMETHANATION", h, td] + layers_in_out["BIO_HYDROLYSIS","GAS"] * F_t ["BIO_HYDROLYSIS", h, td] + layers_in_out["SYN_METHANATION","GAS"] * F_t ["SYN_METHANATION", h, td]
                                  - Storage_in["GAS_STORAGE", "GAS", h, td] ) / 1000 ,
        "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");

}
if F ["GAS_STORAGE"] <= 0.001 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas Prod (3)" , "Gas (5)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}( layers_in_out["GASIFICATION_SNG","GAS"] * F_t ["GASIFICATION_SNG", h, td] + layers_in_out["BIOMETHANATION","GAS"] * F_t ["BIOMETHANATION", h, td] + layers_in_out["BIO_HYDROLYSIS","GAS"] * F_t ["BIO_HYDROLYSIS", h, td] + layers_in_out["SYN_METHANATION","GAS"] * F_t ["SYN_METHANATION", h, td]
                                  - Storage_in["GAS_STORAGE", "GAS", h, td] ) / 1000 ,
        "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["CAR_NG", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "Mob priv", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["CAR_NG","GAS"] * F_t ["CAR_NG", h, td]  ) / 1000 , "GAS", "#FFD700", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["BUS_COACH_CNG_STOICH", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "Mob public", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["BUS_COACH_CNG_STOICH","GAS"] * F_t ["BUS_COACH_CNG_STOICH", h, td]  ) / 1000 ,
        "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["BOAT_FREIGHT_NG", h, td] + F_t ["TRUCK_NG", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "Freight", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["BOAT_FREIGHT_NG","GAS"] * F_t ["BOAT_FREIGHT_NG", h, td] -layers_in_out["TRUCK_NG","GAS"] * F_t ["TRUCK_NG", h, td]  ) / 1000 ,
        "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["SMR", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "H2 prod (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["SMR","GAS"] * F_t ["SMR", h, td]  ) / 1000 , "GAS", "#FFD700", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
}
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["CCGT", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["CCGT","GAS"] * F_t ["CCGT", h, td]  ) / 1000 , "GAS", "#FFD700", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["IND_COGEN_GAS", h, td] + F_t ["DHN_COGEN_GAS", h,
    td] + F_t ["DEC_COGEN_GAS", h, td] + F_t ["DEC_ADVCOGEN_GAS", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "CHP (2)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["IND_COGEN_GAS","GAS"] * F_t ["IND_COGEN_GAS", h, td]   -
        layers_in_out["DHN_COGEN_GAS","GAS"] * F_t ["DHN_COGEN_GAS", h, td]   - layers_in_out["DEC_COGEN_GAS","GAS"] * F_t
        ["DEC_COGEN_GAS", h, td]   - layers_in_out["DEC_ADVCOGEN_GAS","GAS"] * F_t ["DEC_ADVCOGEN_GAS", h, td]  ) /
        1000 , "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["DEC_THHP_GAS", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "HPs (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["DEC_THHP_GAS","GAS"] * F_t ["DEC_THHP_GAS", h, td]  ) / 1000 , "GAS", "#FFD700",
        "TWh" > (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["IND_BOILER_GAS", h, td] + F_t ["DHN_BOILER_GAS", h, td] + F_t ["DEC_BOILER_GAS", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gas (5)" , "Boilers (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["IND_BOILER_GAS","GAS"] * F_t ["IND_BOILER_GAS", h, td]   -
        layers_in_out["DHN_BOILER_GAS","GAS"] * F_t ["DHN_BOILER_GAS", h, td]   - layers_in_out["DEC_BOILER_GAS","GAS"] * F_t
        ["DEC_BOILER_GAS", h, td]  ) / 1000 , "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");

## Electricity production
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["ELECTRICITY", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Electricity (1)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["ELECTRICITY","ELECTRICITY"] * F_t ["ELECTRICITY", h, td]  ) / 1000 ,
        "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["NUCLEAR", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Uranium (1)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}( - layers_in_out["NUCLEAR","URANIUM"] * F_t ["NUCLEAR", h, td]  ) / 1000 , "Nuclear",
        "#FFC0CB", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["WIND_ONSHORE", h, td] + F_t ["WIND_OFFSHORE", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wind (1)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["WIND_ONSHORE","ELECTRICITY"] * F_t ["WIND_ONSHORE", h, td] + layers_in_out["WIND_OFFSHORE","ELECTRICITY"] * F_t ["WIND_OFFSHORE", h, td]  ) / 1000 , "Wind", "#27AE34", "TWh"
        > (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["HYDRO_RIVER", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Hydro River (1)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["HYDRO_RIVER","ELECTRICITY"] * F_t ["HYDRO_RIVER", h, td]   ) / 1000 , "Hydro River", "#0000FF",
        "TWh" > (PathName & "/sankey/input2sankey.csv");

# Coal
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["COAL_US", h, td] + F_t ["COAL_IGCC", h, td]) ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Coal (1)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["COAL_US","COAL"] * F_t ["COAL_US", h, td]   - layers_in_out["COAL_IGCC","COAL"]
        * F_t ["COAL_IGCC", h, td]  ) / 1000 , "Coal", "#A0522D", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["IND_BOILER_COAL", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Coal (1)" , "Boilers (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["IND_BOILER_COAL","COAL"] * F_t ["IND_BOILER_COAL", h, td]  ) / 1000 , "Coal",
        "#A0522D", "TWh" >> (PathName & "/sankey/input2sankey.csv");

# Solar
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["PV", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Solar (1)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["PV","ELECTRICITY"] * F ["PV"] * c_p_t["PV",h,td]  ) / 1000 , "Solar", "#FFFF00", "TWh" >> #From F_t -> F <=> taking into account curtailment
        (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["DEC_SOLAR", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Solar (1)" , "Dec. sto", sum{i in TECHNOLOGIES_OF_END_USES_TYPE["HEAT_LOW_T_DECEN"] diff {"DEC_SOLAR"}, j in TS_OF_DEC_TECH[i], t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                                                                    (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t_solar [i,h,td]/max((layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td]) + layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t_solar [i,h,td],0.0001)
                                                                    * max(Storage_in[j , "HEAT_LOW_T_DECEN", h, td] - Storage_out[j , "HEAT_LOW_T_DECEN", h, td],0 ))/1000,
         "Solar", "#FFFF00", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Solar (1)" , "Heat LT Dec", sum{i in TECHNOLOGIES_OF_END_USES_TYPE["HEAT_LOW_T_DECEN"] diff {"DEC_SOLAR"}, j in TS_OF_DEC_TECH[i], t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t_solar [i,h,td] - (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t_solar [i,h,td]/max((layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td])  + layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t_solar [i,h,td],0.0001)
                                                                    * max(Storage_in[j , "HEAT_LOW_T_DECEN", h, td] - Storage_out[j , "HEAT_LOW_T_DECEN", h, td],0 )))/1000,
         "Solar", "#FFFF00", "TWh" >> (PathName & "/sankey/input2sankey.csv");
        }
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["DHN_SOLAR", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Solar (1)" , "DHN", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["DHN_SOLAR","HEAT_LOW_T_DHN"] * F ["DHN_SOLAR"] * c_p_t["DHN_SOLAR",h,td]  ) / 1000 , "Solar", "#FFFF00", "TWh" >> #From F_t -> F <=> taking into account curtailment
        (PathName & "/sankey/input2sankey.csv");

# Geothermal
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["GEOTHERMAL", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Geothermal (1)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["GEOTHERMAL","ELECTRICITY"] * F_t ["GEOTHERMAL", h, td]  ) / 1000 , "Geothermal",
"#FF0000", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["DHN_DEEP_GEO", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Geothermal (1)" , "DHN", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["DHN_DEEP_GEO","HEAT_LOW_T_DHN"] * F_t ["DHN_DEEP_GEO", h, td]  ) / 1000 ,
"Geothermal", "#FF0000", "TWh" >> (PathName & "/sankey/input2sankey.csv");

# Waste
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["IND_COGEN_WASTE", h, td] + F_t
["DHN_COGEN_WASTE", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Waste (1)" , "CHP (2)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["IND_COGEN_WASTE","WASTE"] * F_t ["IND_COGEN_WASTE", h, td]
        -layers_in_out["DHN_COGEN_WASTE","WASTE"] * F_t ["DHN_COGEN_WASTE", h, td]  ) / 1000 , "Waste", "#808000", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["IND_BOILER_WASTE", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Waste (1)" , "Boilers (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["IND_BOILER_WASTE","WASTE"] * F_t ["IND_BOILER_WASTE", h, td]  ) / 1000 ,
        "Waste", "#808000", "TWh" >> (PathName & "/sankey/input2sankey.csv");

# Oil
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["LFO", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. Oil (0)" , "Oil (1)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (layers_in_out["LFO","LFO"] * F_t ["LFO", h, td]  ) / 1000 , "Oil (1)",
        "#8B008B", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["DEC_COGEN_OIL", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Oil (1)" , "CHP (2)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["DEC_COGEN_OIL","LFO"] * F_t ["DEC_COGEN_OIL", h, td]  ) / 1000 , "Oil (1)",
        "#8B008B", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["IND_BOILER_OIL", h, td] + F_t ["DHN_BOILER_OIL",
h, td] + F_t ["DEC_BOILER_OIL", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Oil (1)" , "Boilers (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["IND_BOILER_OIL","LFO"] * F_t ["IND_BOILER_OIL", h, td]   -
        layers_in_out["DHN_BOILER_OIL","LFO"] * F_t ["DHN_BOILER_OIL", h, td]   - layers_in_out["DEC_BOILER_OIL","LFO"] *
        F_t ["DEC_BOILER_OIL", h, td]  ) / 1000 , "Oil (1)", "#8B008B", "TWh" >> (PathName & "/sankey/input2sankey.csv");

# Wood
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["H2_BIOMASS", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wood (1)" , "H2 prod (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["H2_BIOMASS","WOOD"] * F_t ["H2_BIOMASS", h, td]  ) / 1000 , "Wood", "#CD853F",
        "TWh" > (PathName & "/sankey/input2sankey.csv");

if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["IND_COGEN_WOOD", h, td] + F_t ["DHN_COGEN_WOOD",
h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wood (1)" , "CHP (2)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["IND_COGEN_WOOD","WOOD"] * F_t ["IND_COGEN_WOOD", h, td]   -
        layers_in_out["DHN_COGEN_WOOD","WOOD"] * F_t ["DHN_COGEN_WOOD", h, td]  ) / 1000 , "Wood", "#CD853F", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["IND_BOILER_WOOD", h, td] + F_t
["DHN_BOILER_WOOD", h, td] + F_t ["DEC_BOILER_WOOD", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wood (1)" , "Boilers (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["IND_BOILER_WOOD","WOOD"] * F_t ["IND_BOILER_WOOD", h, td]   -
        layers_in_out["DHN_BOILER_WOOD","WOOD"] * F_t ["DHN_BOILER_WOOD", h, td]   - layers_in_out["DEC_BOILER_WOOD","WOOD"] *
        F_t ["DEC_BOILER_WOOD", h, td]  ) / 1000 , "Wood", "#CD853F", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["GASIFICATION_SNG", h, td] )  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wood (1)" , "Gasifi. (2)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["GASIFICATION_SNG","WOOD"]           * F_t ["GASIFICATION_SNG", h, td] ) / 1000 , "Wood", "#CD853F", "TWh" >(PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gasifi. (2)" , "Gas Prod (3)" , sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}( layers_in_out["GASIFICATION_SNG","GAS"]        * F_t ["GASIFICATION_SNG", h, td] ) / 1000 , "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gasifi. (2)" , "DHN (8)" , sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}( layers_in_out["GASIFICATION_SNG","HEAT_LOW_T_DHN"] * F_t ["GASIFICATION_SNG", h, td] ) / 1000 , "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Gasifi. (2)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}( layers_in_out["GASIFICATION_SNG","ELECTRICITY"]    * F_t ["GASIFICATION_SNG", h, td] ) / 1000 , "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}

# WET Biomass
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["DHN_COGEN_WET_BIOMASS", h, td] + F_t ["DHN_COGEN_BIO_HYDROLYSIS", h, td]) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wet biomass (1)" , "CHP (2)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["DHN_COGEN_WET_BIOMASS","WET_BIOMASS"] * F_t ["DHN_COGEN_WET_BIOMASS", h, td] -layers_in_out["DHN_COGEN_BIO_HYDROLYSIS","WET_BIOMASS"] * F_t ["DHN_COGEN_BIO_HYDROLYSIS", h, td] ) / 1000
        , "Wood", "#CD853F", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["BIOMETHANATION", h, td] + F_t ["BIO_HYDROLYSIS", h, td] ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wet biomass (1)" , "Biomethanation (2)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(- layers_in_out["BIOMETHANATION","WET_BIOMASS"] * F_t ["BIOMETHANATION", h, td] - layers_in_out["BIO_HYDROLYSIS","WET_BIOMASS"] * F_t ["BIO_HYDROLYSIS", h, td] ) / 1000
        , "Wood", "#CD853F", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Biomethanation (2)" , "Gas Prod (3)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(  layers_in_out["BIOMETHANATION","GAS"]          * F_t ["BIOMETHANATION", h, td] + layers_in_out["BIO_HYDROLYSIS","GAS"]          * F_t ["BIO_HYDROLYSIS", h, td] ) / 1000 ,
        "GAS", "#FFD700", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["BIO_HYDROLYSIS", h, td] ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Biomethanation (2)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["BIO_HYDROLYSIS","ELECTRICITY"] * F_t ["BIO_HYDROLYSIS", h, td] ) / 1000
        , "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");

#------------------------------------------
# SANKEY - Electricity use
#------------------------------------------
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["CAR_PHEV", h, td] + F_t ["CAR_BEV", h, td]) ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Mob priv", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["CAR_PHEV","ELECTRICITY"] * F_t ["CAR_PHEV", h, td]   -
        layers_in_out["CAR_BEV","ELECTRICITY"] * F_t ["CAR_BEV", h, td]  ) / 1000 , "Electricity", "#00BFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["TRAIN_PUB", h, td] + F_t ["TRAMWAY_TROLLEY", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Mob public", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["TRAIN_PUB","ELECTRICITY"] * F_t ["TRAIN_PUB", h, td]   -
        layers_in_out["TRAMWAY_TROLLEY","ELECTRICITY"] * F_t ["TRAMWAY_TROLLEY", h, td]  ) / 1000 , "Electricity", "#00BFFF",
        "TWh" > (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["TRAIN_FREIGHT", h, td] + F_t ["TRUCK_ELEC", h, td])  > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Freight", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["TRAIN_FREIGHT","ELECTRICITY"] * F_t ["TRAIN_FREIGHT", h, td] -layers_in_out["TRUCK_ELEC","ELECTRICITY"] * F_t ["TRUCK_ELEC", h, td]  ) / 1000 ,
        "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(Network_losses ["ELECTRICITY", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Exp & Loss", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(Network_losses
        ["ELECTRICITY", h, td]     ) / 1000
        , "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["ELEC_EXPORT", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Curt.", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (-layers_in_out["ELEC_EXPORT","ELECTRICITY"] * F_t ["ELEC_EXPORT", h, td]     ) / 1000
        , "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
#if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(End_uses ["ELECTRICITY", h, td]  ) > 10 then
#    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Elec demand", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(End_uses
#        ["ELECTRICITY", h, td]  - Network_losses ["ELECTRICITY", h, td] - sum {i in STORAGE_OF_END_USES_TYPES["ELECTRICITY"]} (max(Storage_out [i, "ELECTRICITY", h, td] - Storage_in [i, "ELECTRICITY", h, td],0))
#        )/ 1000 , "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
#In case of curtailment ( F_t < F * c_p_t) solar & wind
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F["PV"]*c_p_t["PV",h,td] -  F_t["PV",h,td]) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Solar (1)" , "Curt.", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (F["PV"]*c_p_t["PV",h,td] -  F_t["PV",h,td])  / 1000
        , "Solar", "#FFFF00", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F["WIND_ONSHORE"]*c_p_t["WIND_ONSHORE",h,td] -  F_t["WIND_ONSHORE",h,td] + F["WIND_OFFSHORE"]*c_p_t["WIND_OFFSHORE",h,td] -  F_t["WIND_OFFSHORE",h,td]) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wind (1)" , "Curt.", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (F["WIND_ONSHORE"]*c_p_t["WIND_ONSHORE",h,td] -  F_t["WIND_ONSHORE",h,td] + F["WIND_OFFSHORE"]*c_p_t["WIND_OFFSHORE",h,td] -  F_t["WIND_OFFSHORE",h,td])  / 1000
        , "Wind", "#27AE34", "TWh"  > (PathName & "/sankey/input2sankey.csv");
# New boxes for Electricity storage
if sum{i in STORAGE_OF_END_USES_TYPES["ELECTRICITY"], t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(Storage_in [i, "ELECTRICITY", h, td]) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Storage", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}       (sum {i
        in STORAGE_OF_END_USES_TYPES["ELECTRICITY"] } max(- Storage_out [i, "ELECTRICITY", h, td] + Storage_in [i, "ELECTRICITY", h, td] ,0))/ 1000 , "Electricity", "#00BFFF",
        "TWh" > (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Storage (5)" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(sum {i
        in STORAGE_OF_END_USES_TYPES["ELECTRICITY"] } max(+ Storage_out [i, "ELECTRICITY", h, td] - Storage_in [i, "ELECTRICITY", h, td] ,0))/ 1000 , "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
# Electrification of heat
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["DHN_HP_ELEC", h, td] + F_t ["DEC_HP_ELEC", h, td]) ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "HPs (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (-layers_in_out["DHN_HP_ELEC","ELECTRICITY"] * F_t ["DHN_HP_ELEC", h, td]
         -layers_in_out["DEC_HP_ELEC","ELECTRICITY"] * F_t ["DEC_HP_ELEC", h, td]  )
         / 1000 , "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["DEC_DIRECT_ELEC", h, td]  ) > 10 then {
    if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} max(Storage_in["TS_DEC_DIRECT_ELEC" , "HEAT_LOW_T_DECEN", h, td] - Storage_out["TS_DEC_DIRECT_ELEC" , "HEAT_LOW_T_DECEN", h, td],0 ) > 10 then {
        printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Dec. sto", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                                                                                                ((layers_in_out["DEC_DIRECT_ELEC","HEAT_LOW_T_DECEN"] * F_t ["DEC_DIRECT_ELEC",h,td]/max((layers_in_out["DEC_DIRECT_ELEC","HEAT_LOW_T_DECEN"] * F_t ["DEC_DIRECT_ELEC",h,td]) + layers_in_out["DEC_DIRECT_ELEC","HEAT_LOW_T_DECEN"] * F_t_solar ["DEC_DIRECT_ELEC",h,td],0.0001)
                                                                                                * max(Storage_in["TS_DEC_DIRECT_ELEC" , "HEAT_LOW_T_DECEN", h, td] - Storage_out["TS_DEC_DIRECT_ELEC" , "HEAT_LOW_T_DECEN", h, td],0 )))/1000,
        "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    }
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Heat LT Dec", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        ((layers_in_out["DEC_DIRECT_ELEC","HEAT_LOW_T_DECEN"] * F_t ["DEC_DIRECT_ELEC",h,td]) - (layers_in_out["DEC_DIRECT_ELEC","HEAT_LOW_T_DECEN"] * F_t ["DEC_DIRECT_ELEC",h,td]/max((layers_in_out["DEC_DIRECT_ELEC","HEAT_LOW_T_DECEN"] * F_t ["DEC_DIRECT_ELEC",h,td]) + layers_in_out["DEC_DIRECT_ELEC","HEAT_LOW_T_DECEN"] * F_t_solar ["DEC_DIRECT_ELEC",h,td],0.0001)
                                                                                            * max(Storage_in["TS_DEC_DIRECT_ELEC" , "HEAT_LOW_T_DECEN", h, td] - Storage_out["TS_DEC_DIRECT_ELEC" , "HEAT_LOW_T_DECEN", h, td],0 )))/1000,
          "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["IND_DIRECT_ELEC", h, td]  ) > 10 then {
    if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} max(Storage_in["TS_HIGH_TEMP" , "HEAT_HIGH_T", h, td] - Storage_out["TS_HIGH_TEMP" , "HEAT_HIGH_T", h, td],0 ) > 10 then {
        printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "HT sto", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                                                                                                max(storage_eff_in["TS_HIGH_TEMP" , "HEAT_HIGH_T"] * Storage_in["TS_HIGH_TEMP" , "HEAT_HIGH_T", h, td] - Storage_out["TS_HIGH_TEMP" , "HEAT_HIGH_T", h, td],0 )/1000,
               "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
        printf "%s,%s,%.2f,%s,%s,%s\n", "HT sto (8)", "Heat HT (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                                                                                                max(storage_eff_out["TS_HIGH_TEMP" , "HEAT_HIGH_T"] * Storage_out["TS_HIGH_TEMP" , "HEAT_HIGH_T", h, td] - Storage_in["TS_HIGH_TEMP" , "HEAT_HIGH_T", h, td],0 )/1000,
               "Heat HT", "#DC143C", "TWh", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    }
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Heat HT (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                                                             (F_t ["IND_DIRECT_ELEC", h, td]	  - max(storage_eff_in["TS_HIGH_TEMP" , "HEAT_HIGH_T"] * Storage_in["TS_HIGH_TEMP" , "HEAT_HIGH_T", h, td] - Storage_out["TS_HIGH_TEMP" , "HEAT_HIGH_T", h, td],0 ))/1000,
           "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
# Electrolysis
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["H2_ELECTROLYSIS", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Electrolyser (8)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["H2_ELECTROLYSIS","ELECTRICITY"] * F_t ["H2_ELECTROLYSIS", h, td]  ) / 1000 ,
        "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Heat HT (7)" , "Electrolyser (8)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(- layers_in_out["H2_ELECTROLYSIS","HEAT_HIGH_T"] * F_t ["H2_ELECTROLYSIS", h, td]  ) / 1000 ,
        "Heat HT", "#DC143C", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Electrolyser (8)" , "H2 prod (6)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["H2_ELECTROLYSIS","H2"] * F_t ["H2_ELECTROLYSIS", h, td]  ) / 1000 ,
        "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Electrolyser (8)" , "DHN", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["H2_ELECTROLYSIS","HEAT_LOW_T_DHN"] * F_t ["H2_ELECTROLYSIS", h, td]  ) / 1000 ,
        "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}

#------------------------------------------
# Synthetic fuels use
#------------------------------------------
## H2 use
if sum {t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["H2", h, td] * t_op [h, td]) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. H2 (0)" , "H2", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(F_t ["H2", h, td] * t_op [h, td]) / 1000 , "H2", "#FF00FF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
if sum {t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (F_t ["H2_RE", h, td] * t_op [h, td]) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Imp. H2 (0) RE" , "H2", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(F_t ["H2_RE", h, td] * t_op [h, td]) / 1000 , "H2", "#FF00FF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
if F ["H2_STORAGE"] > 0.001 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2 prod (6)" , "H2 sto.", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(Storage_in["H2_STORAGE", "H2", h, td]  ) / 1000 ,
        "H2", "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2 sto." , "H2", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(Storage_out["H2_STORAGE", "H2", h, td]*storage_eff_out ["H2_STORAGE","H2"]  ) / 1000 ,
        "H2", "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2 prod (6)" , "H2", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}( layers_in_out["SMR","H2"] * F_t ["SMR", h, td] + layers_in_out["H2_BIOMASS","H2"] * F_t ["H2_BIOMASS", h, td] + layers_in_out["H2_ELECTROLYSIS","H2"] * F_t ["H2_ELECTROLYSIS", h, td]
                                    - Storage_in["H2_STORAGE", "H2", h, td]) / 1000 ,
        "H2", "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    }
else{if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}( F_t ["SMR", h, td] + F_t ["H2_BIOMASS", h, td] + F_t ["H2_ELECTROLYSIS", h, td]) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2 prod (6)" , "H2", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}( layers_in_out["SMR","H2"] * F_t ["SMR", h, td] + layers_in_out["H2_BIOMASS","H2"] * F_t ["H2_BIOMASS", h, td] + layers_in_out["H2_ELECTROLYSIS","H2"] * F_t ["H2_ELECTROLYSIS", h, td]) / 1000 ,
        "H2", "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["DEC_ADVCOGEN_H2", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2" , "CHP (2)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["DEC_ADVCOGEN_H2","H2"] * F_t ["DEC_ADVCOGEN_H2", h, td]  ) / 1000 , "H2",
        "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["CAR_FUEL_CELL", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2" , "Mob priv", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["CAR_FUEL_CELL","H2"] * F_t ["CAR_FUEL_CELL", h, td]  ) / 1000 , "H2",
        "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["BUS_COACH_FC_HYBRIDH2", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2" , "Mob public", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["BUS_COACH_FC_HYBRIDH2","H2"] * F_t ["BUS_COACH_FC_HYBRIDH2", h, td]  ) / 1000 ,
        "H2", "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["TRUCK_FUEL_CELL", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2" , "Freight", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["TRUCK_FUEL_CELL","H2"] * F_t ["TRUCK_FUEL_CELL", h, td]  ) / 1000 ,
        "H2", "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["SYN_METHANATION", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2" , "Gas Prod (3)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["SYN_METHANATION","H2"] * F_t ["SYN_METHANATION", h, td]  ) / 1000 ,
        "H2", "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t ["SYN_METHANOLATION", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "H2" , "Biofuels Prod", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(-layers_in_out["SYN_METHANOLATION","H2"] * F_t ["SYN_METHANOLATION", h, td]  ) / 1000 ,
        "H2", "#FF00FF", "TWh" >> (PathName & "/sankey/input2sankey.csv");

#------------------------------------------
# SANKEY - HEATING
#------------------------------------------
# CHP (2)
if sum{i in COGEN, t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(F_t [ i, h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "CHP (2)" , "Elec (7)", sum{i in COGEN, t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out[i,"ELECTRICITY"] * F_t [i, h, td]  ) / 1000 , "Electricity", "#00BFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["DEC_COGEN_GAS", h, td] + F_t ["DEC_COGEN_OIL", h,td] + F_t ["DEC_ADVCOGEN_GAS", h, td] + F_t ["DEC_ADVCOGEN_H2", h, td])  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "CHP (2)" , "Dec. sto", sum{i in {"DEC_COGEN_GAS","DEC_COGEN_OIL","DEC_ADVCOGEN_GAS","DEC_ADVCOGEN_H2"}, j in TS_OF_DEC_TECH[i],t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                                                                    (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td]/max((layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td]) + layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t_solar [i,h,td],0.0001)
                                                                                            * max(Storage_in[j , "HEAT_LOW_T_DECEN", h, td] - Storage_out[j , "HEAT_LOW_T_DECEN", h, td],0 ))/1000,
         "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "CHP (2)" , "Heat LT Dec", sum{i in {"DEC_COGEN_GAS","DEC_COGEN_OIL","DEC_ADVCOGEN_GAS","DEC_ADVCOGEN_H2"}, j in TS_OF_DEC_TECH[i],t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
            (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td] - (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td]/max((layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td]) + layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t_solar [i,h,td],0.0001)
                                                                                            * max(Storage_in[j , "HEAT_LOW_T_DECEN", h, td] - Storage_out[j , "HEAT_LOW_T_DECEN", h, td],0 ))) /1000,
         "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["DHN_COGEN_GAS", h, td] + F_t ["DHN_COGEN_WOOD",
h, td] + F_t ["DHN_COGEN_WASTE", h, td]) + F_t ["DHN_COGEN_WET_BIOMASS", h, td] + F_t ["DHN_COGEN_BIO_HYDROLYSIS", h, td])   > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "CHP (2)" , "DHN", sum{i in COGEN, t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out[i,"HEAT_LOW_T_DHN"] * F_t [i, h, td]  ) / 1000 , "Heat LT", "#FA8072", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["IND_COGEN_GAS", h, td] + F_t ["IND_COGEN_WOOD",
h, td] + F_t ["IND_COGEN_WASTE", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "CHP (2)" , "Heat HT", sum{i in COGEN, t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out[i,"HEAT_HIGH_T"] * F_t [i, h, td]  ) / 1000 , "Heat HT", "#DC143C", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");

# HPs (6)
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} ((F_t ["DEC_HP_ELEC", h, td] + F_t ["DEC_THHP_GAS", h, td])  ) > 10 then {
    if sum{i in {"DEC_HP_ELEC","DEC_THHP_GAS"}, j in TS_OF_DEC_TECH[i], t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (max(Storage_in[j , "HEAT_LOW_T_DECEN", h, td] - Storage_out[j , "HEAT_LOW_T_DECEN", h, td],0 )) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "HPs (6)" , "Dec. sto", sum{i in {"DEC_HP_ELEC","DEC_THHP_GAS"}, j in TS_OF_DEC_TECH[i], t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                                                                    (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td]/max((layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td]) + layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t_solar [i,h,td],0.0001)
                                                                                            * max(Storage_in[j , "HEAT_LOW_T_DECEN", h, td] - Storage_out[j , "HEAT_LOW_T_DECEN", h, td],0 ))/1000,
         "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    }
    printf "%s,%s,%.2f,%s,%s,%s\n", "HPs (6)" , "Heat LT Dec", sum{i in {"DEC_HP_ELEC","DEC_THHP_GAS"}, j in TS_OF_DEC_TECH[i], t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
            (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td] - (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td]/max((layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td]) + layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t_solar [i,h,td],0.0001)
                                                                                            * max(Storage_in[j , "HEAT_LOW_T_DECEN", h, td] - Storage_out[j , "HEAT_LOW_T_DECEN", h, td],0 )))/1000,
         "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} F_t ["DHN_HP_ELEC", h, td]  > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "HPs (6)" , "DHN", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (layers_in_out["DHN_HP_ELEC","HEAT_LOW_T_DHN"] * F_t ["DHN_HP_ELEC",h,td])/1000,
         "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");

# Biofuels
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["PYROLYSIS_TO_LFO", h, td])  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wood" , "Pyrolysis", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}( - layers_in_out["PYROLYSIS_TO_LFO","WOOD"] * F_t ["PYROLYSIS_TO_LFO", h, td]  ) / 1000 , "Wood", "#CD853F", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Pyrolysis" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["PYROLYSIS_TO_LFO","ELECTRICITY"] * F_t ["PYROLYSIS_TO_LFO", h, td]  ) / 1000 , "Electricity", "#00BFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    #printf "%s,%s,%.2f,%s,%s,%s\n", "Pyrolysis" , "Oil (1)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
    #    TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["PYROLYSIS_TO_LFO","OIL"] * F_t ["PYROLYSIS_TO_LFO", h, td]  ) / 1000 , "Oil (1)", "#8B008B", "TWh" >>
    #    (PathName & "/sankey/input2sankey.csv");
}
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["PYROLYSIS_TO_FUELS", h, td])  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Wood" , "Pyrolysis", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}( - layers_in_out["PYROLYSIS_TO_FUELS","WOOD"] * F_t ["PYROLYSIS_TO_FUELS", h, td]  ) / 1000 , "Wood", "#CD853F", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Pyrolysis" , "Elec (7)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["PYROLYSIS_TO_FUELS","ELECTRICITY"] * F_t ["PYROLYSIS_TO_FUELS", h, td]  ) / 1000 , "Electricity", "#00BFFF", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Pyrolysis" , "Diesel (1)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["PYROLYSIS_TO_FUELS","DIESEL"] * F_t ["PYROLYSIS_TO_FUELS", h, td]  ) / 1000 , "Diesel (1)", "#D3D3D3", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Pyrolysis" , "Gasoline (1)", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out["PYROLYSIS_TO_FUELS","GASOLINE"] * F_t ["PYROLYSIS_TO_FUELS", h, td]  ) / 1000 , "Diesel (1)", "#808080", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");
}


# Boilers (6)
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["DEC_BOILER_GAS", h, td] + F_t ["DEC_BOILER_WOOD",
h, td] + F_t ["DEC_BOILER_OIL", h, td])  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Boilers (6)" , "Dec. sto",
        sum{i in {"DEC_BOILER_GAS","DEC_BOILER_OIL","DEC_BOILER_WOOD"}, j in TS_OF_DEC_TECH[i], t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
            max(Storage_in[j , "HEAT_LOW_T_DECEN", h, td] - Storage_out[j , "HEAT_LOW_T_DECEN", h, td],0)/1000,
        "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "Boilers (6)" , "Heat LT Dec",
        sum{i in {"DEC_BOILER_GAS","DEC_BOILER_OIL","DEC_BOILER_WOOD"}, j in TS_OF_DEC_TECH[i], t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
            (layers_in_out[i,"HEAT_LOW_T_DECEN"] * F_t [i,h,td] - max(Storage_in[j , "HEAT_LOW_T_DECEN", h, td] - Storage_out[j , "HEAT_LOW_T_DECEN", h, td],0))/1000,
        "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}
if sum {t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t], i in STORAGE_OF_END_USES_TYPES["HEAT_LOW_T_DECEN"]} max(Storage_out[i , "HEAT_LOW_T_DECEN", h, td] - Storage_in[i , "HEAT_LOW_T_DECEN", h, td],0) > 10 then
   printf "%s,%s,%.2f,%s,%s,%s\n", "Dec. sto" , "Heat LT Dec", sum {t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t], i in STORAGE_OF_END_USES_TYPES["HEAT_LOW_T_DECEN"]}
                        max(Storage_out[i , "HEAT_LOW_T_DECEN", h, td] - Storage_in[i , "HEAT_LOW_T_DECEN", h, td],0)/1000 , "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");

if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["DHN_BOILER_GAS", h, td] + F_t ["DHN_BOILER_WOOD",
h, td] + F_t ["DHN_BOILER_OIL", h, td])  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Boilers (6)" , "DHN", sum{i in BOILERS, t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out[i,"HEAT_LOW_T_DHN"] * F_t [i, h, td]  ) / 1000 , "Heat LT", "#FA8072", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");

if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}((F_t ["IND_BOILER_GAS", h, td] + F_t ["IND_BOILER_WOOD",
h, td] + F_t ["IND_BOILER_OIL", h, td] + F_t ["IND_BOILER_COAL", h, td] + F_t ["IND_BOILER_WASTE", h, td])  ) > 10	then
    printf "%s,%s,%.2f,%s,%s,%s\n", "Boilers (6)" , "Heat HT", sum{i in BOILERS, t in PERIODS, h in HOUR_OF_PERIOD[t], td in
        TYPICAL_DAY_OF_PERIOD[t]}(layers_in_out[i,"HEAT_HIGH_T"] * F_t [i, h, td]  ) / 1000 , "Heat HT", "#DC143C", "TWh" >>
        (PathName & "/sankey/input2sankey.csv");

# DHN
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(End_uses ["HEAT_LOW_T_DHN", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "DHN" , "Heat LT DHN", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (sum {i in TECHNOLOGIES diff STORAGE_TECH } (layers_in_out[i, "HEAT_LOW_T_DHN"] * F_t [i, h, td]  )
        - Network_losses ["HEAT_LOW_T_DHN", h, td]
        - sum {i in STORAGE_OF_END_USES_TYPES["HEAT_LOW_T_DHN"]} max(Storage_in  [i, "HEAT_LOW_T_DHN", h, td] - Storage_out  [i, "HEAT_LOW_T_DHN", h, td],0)) / 1000
        , "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(Network_losses ["HEAT_LOW_T_DHN", h, td]  ) > 10 then
    printf "%s,%s,%.2f,%s,%s,%s\n", "DHN" , "Loss DHN", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (Network_losses ["HEAT_LOW_T_DHN", h, td]  ) / 1000 , "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
if sum {i in STORAGE_OF_END_USES_TYPES["HEAT_LOW_T_DHN"] ,t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
max(Storage_in  [i, "HEAT_LOW_T_DHN", h, td] - Storage_out  [i, "HEAT_LOW_T_DHN", h, td],0) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "DHN" , "DHN Sto", sum {i in STORAGE_OF_END_USES_TYPES["HEAT_LOW_T_DHN"],t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} max(Storage_in  [i, "HEAT_LOW_T_DHN", h, td] - Storage_out  [i, "HEAT_LOW_T_DHN", h, td],0)/1000
        , "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
    printf "%s,%s,%.2f,%s,%s,%s\n", "DHN Sto", "Heat LT DHN", sum {i in STORAGE_OF_END_USES_TYPES["HEAT_LOW_T_DHN"],t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} max(Storage_out  [i, "HEAT_LOW_T_DHN", h, td] - Storage_in  [i, "HEAT_LOW_T_DHN", h, td],0)/1000
        , "Heat LT", "#FA8072", "TWh" >> (PathName & "/sankey/input2sankey.csv");
}

# Ind Heat Demand
if sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]} (End_uses ["HEAT_HIGH_T", h, td]  ) > 10 then {
    printf "%s,%s,%.2f,%s,%s,%s\n", "Heat HT" , "Ind Heat Demand", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
                            End_uses ["HEAT_HIGH_T", h, td]   / 1000 , "Heat HT", "#DC143C", "TWh"
    >> (PathName & "/sankey/input2sankey.csv");
}


#------------------------------------------
# SANKEY - LIGHT
#------------------------------------------
printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Light Bulb", (-layers_in_out["LIGHT","ELECTRICITY"]*end_uses_sankey["LIGHT"])
         / 1000 , "Electricity", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
printf "%s,%s,%.2f,%s,%s,%s\n", "Light Bulb" , "Light", (end_uses_sankey["LIGHT"])/
1000 , "Electricity", "#feff00", "TWh" >> (PathName & "/sankey/input2sankey.csv");

}
#------------------------------------------
# SANKEY - COOLING
#------------------------------------------

printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Fridge",(-layers_in_out["FRIDGE","ELECTRICITY"]*end_uses_sankey["FOOD_COOLING"])
         / 1000 , "Cold", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
printf "%s,%s,%.2f,%s,%s,%s\n", "Fridge" , "Food Cooling", end_uses_sankey["FOOD_COOLING"]/ 1000 , "Cold", "#00ffc0", "TWh" >> (PathName & "/sankey/input2sankey.csv");

printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "AC", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
        (-layers_in_out["ELEC_REFRIG_CYCLE","ELECTRICITY"]*F_t ["ELEC_REFRIG_CYCLE", h, td]
        - layers_in_out["TH_REFRIG_CYCLE","ELECTRICITY"]*F_t ["TH_REFRIG_CYCLE", h, td])
         / 1000 , "Cold", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
printf "%s,%s,%.2f,%s,%s,%s\n", "AC" , "Space Cooling", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(End_uses
        ["SPACE_COOLING", h, td])/ 1000 , "Cold", "#00ffc0", "TWh" >> (PathName & "/sankey/input2sankey.csv");



printf "%s,%s,%.2f,%s,%s,%s\n", "Industrial Elec Cooler" , "Industrial Cooling", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}(End_uses
    ["PROCESS_COOLING", h, td])/ 1000 , "Cold", "#00ffc0", "TWh" >> (PathName & "/sankey/input2sankey.csv");
printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Industrial Elec Cooler", sum{t in PERIODS, h in HOUR_OF_PERIOD[t], td in TYPICAL_DAY_OF_PERIOD[t]}
    (-layers_in_out["IND_ELEC_COOLING","ELECTRICITY"]*F_t ["IND_ELEC_COOLING", h, td])
     / 1000 , "Cold", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");




#+F_t ["ELEC_REFRIG_SPACE", h, td]) + F_t ["TH_REFRIG_CYCLE", h, td]) + F_t ["IND_ELEC_COOLING", h, td])
#------------------------------------------
# SANKEY - MECHANICAL DRIVE
#------------------------------------------


printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Electrical Motor",
    (-layers_in_out["MEC_DRIVE","ELECTRICITY"]*end_uses_sankey["MEC_DRIVE"])
     / 1000 , "Elec_motor", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
printf "%s,%s,%.2f,%s,%s,%s\n", "Electrical Motor" , "Mechanical Drive", end_uses_sankey["MEC_DRIVE"]/ 1000 , "Mechanical Drive", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");


#------------------------------------------
# SANKEY - OTHER ELEC USES
#------------------------------------------
printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Plug",
    (-layers_in_out["OTHERS_ELEC","ELECTRICITY"]*end_uses_sankey["OTHERS_ELEC"])
     / 1000 , "Other_Elec", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
printf "%s,%s,%.2f,%s,%s,%s\n", "Plug" , "Other Elec", end_uses_sankey["OTHERS_ELEC"]/ 1000 , "Other_Elec", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");


#------------------------------------------
# SANKEY - RESIDENTIAL HEAT
#------------------------------------------

printf "%s,%s,%.2f,%s,%s,%s\n", "Elec (7)" , "Electric Resistance",
    (-layers_in_out["HEAT_RES","ELECTRICITY"]*end_uses_sankey["HEAT_RES"])
     / 1000 , "Residential heat", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");
printf "%s,%s,%.2f,%s,%s,%s\n", "Electric Resistance" , "Residential heat", end_uses_sankey["HEAT_RES"]/ 1000 , "Residential heat", "#00BFFF", "TWh" >> (PathName & "/sankey/input2sankey.csv");

